keys:
  - &at_ithinuel F1DA07835BA76FA450BBCA2B0BC4C0B2B0879D6A
  - &at_work 9F2D999DD7C7CCCFA7A5B357FD66024FC8A1D433
  - &tleilax age139cukquufmk8yt9zg5s07z8sw6kdcwxr59zntmumd682c96wde7sq4a8v5
  - &tleilax_user age1qkzwzwutk8ddylflts5r7qvu7lhgr0zeh880r9tu8fsg3g5s84wsjep8vh
  - &ix age13gm6x5tru5x48yhvgwvwrc5grfnu8cpdlpd39jy6dpsmt9u2qq2qjfd7v6
  - &ix_user age1vy6utcttelw3ykae97ms0v9s8ph6g96q892hc45qhftvpt2cs58q7ggjj8
creation_rules:
  - path_regex: secrets/tleilax\..*\.sops
    pgp: *at_ithinuel
    age: *tleilax
  - path_regex: secrets/ix\..*\.sops
    pgp: *at_ithinuel
    age: *ix
  - path_regex: secrets/allowed_signers.sops
    key_groups:
      - pgp:
          - *at_ithinuel
        age:
          - *tleilax_user
          - *ix_user
  - path_regex: secrets/.*$
    key_groups:
      - pgp:
          - *at_ithinuel
          - *at_work
